# Generated by Django 3.0.3 on 2020-07-23 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='state',
            field=models.TextField(default='SOME STRING'),
        ),
    ]
